services:
  - type: web
    name: bank-hazard-dashboard
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.9.0
      - key: NODE_ENV
        value: production
